services:
  mongo:
    container_name: flask_mongo
    image: mongo:8.0-rc
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017" # Expondo a porta do MongoDB
    volumes:
      - mongo-data:/data/db # Volume para persistir os dados do MongoDB

volumes:
  mongo-data: # Definindo o volume para persistência de dados do MongoDB
